### ISSUE TITLE
No audio (aac latm)

### ISSUE THREAD

**Issue by dhead666** [BtbN/vlc-htsp-plugin#3]
No audio in vlc with vlc-htpc-plugin.

Audio is recognized on xbmc, tvhguide (played in mxplayer).
When directly openning the network stream audio is recoginzed but I do get the following error messege which I believe is because of the the subtitles.

On vlc codec information tag: 
Stream 0: Video, h264.
Streams 1+2: Audio, AAC LATM.
Streams 3-5: Subtitles ("codec": undf)

>No suitable decoder module:
>VLC does not support the audio or video format "undf". Unfortunately there is no >way for you to fix this.

Tested on linux x86-64, vlc 2.0.6, tvheadend from master git branch last commit from 13.04.2013

**Comment by fape** [comment]
I got the same. Directly open from "Broadcast details" everything works fine, but when I open from vlc's library there is no sound.
May be this can help: http://i.imgur.com/6VW3hf9.png

What am I miss?

**Comment by fape** [comment]
I did some research. I think there is some "magic" if the audio stream is mpeg2. I mean "automatic codec information detection/correction"
Because when I comment out these 2 line access.cpp#L789, the mpeg2 stream is still working.
The map->getU32("channels") returns 2 for both stream (mpeg2 and aac). 
I find some #define s about channels in vlc_es.h (#define AOUT_CHAN_*)
AND the map->getU32("rate") always return below 10 (tipicaly 3 or 6) not 48000 as the codec info shows.
I think something mapping is missing.
Where can I find some information how to map channels and rate infos?

**Comment by dhead666** [comment]
After [this commit](https://github.com/tvheadend/tvheadend/commit/cc1fbb02028c4e5baaf72deaa01b34748686e273) audio track is audible of most channels (I don't have much) but it's not continuous completely, I can notice blips of silents (not sure what to call it).

**Comment by BtbN** [comment]
There is absolutely nothing i could do about that, i just pass the raw data to VLC without touching it.

**Comment by dhead666** [comment]
@BtbN 

Let me know if you need more samples and you can actually also use the stream link of WRKZ radio station to encounter the current issue of audio gliches with aac.
```
pipe:///usr/bin/ffmpeg -loglevel fatal -i http://icy3.abacast.com/nabco-wrkzfmaac-48 -vn -acodec copy -metadata service_provider=IPTV -metadata service_name=BLITZ -f mpegts pipe:1
```

**Comment by dhead666** [comment]
The original issue has been fixed with latest commits.
There's another issue with buffer underruns (the audio gliches/hiccups) which @BtbN is aware of and hopefully will be fixed soon.
